[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224
    Tag           synapse.core

[FILTER]
    Name          parser
    Match         synapse.core
    Key_Name      log
    Parser        synapse_json
    Reserve_Data  On
    Preserve_Key  Off

[OUTPUT]
    Name          loki
    Match         synapse.core
    Host          ${LOKI_HOST}
    Port          ${LOKI_PORT}
    URI           /loki/api/v1/push
    Labels        service=synapse-core,environment=${APP_ENV}
    Line_Format   json