//! SDK/CLI/API compatibility matrix: parses `COMPATIBILITY.toml` (the
//! structured source of truth) and renders it to `docs/compatibility-matrix.md`.
//!
//! Deliberately hand-rolled rather than pulling in a `toml` crate dependency
//! — `COMPATIBILITY.toml` is generated/maintained by this same module, so it
//! only ever needs to round-trip our own narrow `[[entry]]` shape, not
//! arbitrary TOML.

use clap::{Args, Subcommand};
use std::fs;
use std::path::Path;

const MATRIX_PATH: &str = "COMPATIBILITY.toml";
const RENDERED_PATH: &str = "docs/compatibility-matrix.md";

#[derive(Args)]
pub struct CompatMatrixArgs {
    #[command(subcommand)]
    pub command: CompatMatrixCommand,
}

#[derive(Subcommand)]
pub enum CompatMatrixCommand {
    /// Render COMPATIBILITY.toml into docs/compatibility-matrix.md.
    Render,
    /// Fail if docs/compatibility-matrix.md is out of date with COMPATIBILITY.toml.
    Check,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct CompatEntry {
    pub sdk_version: String,
    pub cli_version: String,
    pub api_versions: Vec<String>,
    pub notes: String,
}

pub fn run(args: CompatMatrixArgs) -> anyhow::Result<()> {
    match args.command {
        CompatMatrixCommand::Render => {
            let rendered = render_from_file(MATRIX_PATH)?;
            fs::write(RENDERED_PATH, &rendered)?;
            println!("✓ Wrote {RENDERED_PATH}");
            Ok(())
        }
        CompatMatrixCommand::Check => {
            let rendered = render_from_file(MATRIX_PATH)?;
            let on_disk = fs::read_to_string(RENDERED_PATH).unwrap_or_default();
            if rendered != on_disk {
                anyhow::bail!(
                    "{RENDERED_PATH} is out of date with {MATRIX_PATH}. \
                     Run `cargo xtask compat-matrix render` and commit the result."
                );
            }
            println!("✓ {RENDERED_PATH} is up to date.");
            Ok(())
        }
    }
}

/// Used by `xtask release` as a pre-flight check: fail the release if no
/// entry in the compatibility matrix covers the version being released.
pub fn ensure_matrix_has_entry_for(version: &str) -> anyhow::Result<()> {
    let entries = parse_entries(&fs::read_to_string(MATRIX_PATH)?);
    let covered = entries
        .iter()
        .any(|e| e.sdk_version == version || e.cli_version == version);
    if !covered {
        anyhow::bail!(
            "No entry in {MATRIX_PATH} has sdk_version or cli_version = \"{version}\". \
             Add one (and run `cargo xtask compat-matrix render`) before releasing."
        );
    }
    Ok(())
}

fn render_from_file(path: impl AsRef<Path>) -> anyhow::Result<String> {
    let content = fs::read_to_string(path)?;
    Ok(render(&parse_entries(&content)))
}

fn render(entries: &[CompatEntry]) -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by `cargo xtask compat-matrix render` from COMPATIBILITY.toml. Do not edit by hand. -->\n\n");
    out.push_str("# SDK / CLI / API Compatibility Matrix\n\n");
    out.push_str("| SDK version | CLI version | Supported API versions | Notes |\n");
    out.push_str("|-------------|-------------|-------------------------|-------|\n");
    for e in entries {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            e.sdk_version,
            e.cli_version,
            e.api_versions.join(", "),
            e.notes
        ));
    }
    out
}

/// Parses our own narrow `[[entry]]` block shape:
/// `[[entry]]` header followed by `key = "value"` or `key = ["a", "b"]`
/// lines, terminated by the next `[[entry]]` or end of file. Comment lines
/// (`#`) and blank lines are ignored.
fn parse_entries(content: &str) -> Vec<CompatEntry> {
    let mut entries = Vec::new();
    let mut block: Option<Vec<&str>> = None;

    for raw_line in content.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "[[entry]]" {
            if let Some(lines) = block.take() {
                entries.push(parse_block(&lines));
            }
            block = Some(Vec::new());
        } else if let Some(lines) = block.as_mut() {
            lines.push(line);
        }
    }
    if let Some(lines) = block {
        entries.push(parse_block(&lines));
    }
    entries
}

fn parse_block(lines: &[&str]) -> CompatEntry {
    let mut sdk_version = String::new();
    let mut cli_version = String::new();
    let mut api_versions = Vec::new();
    let mut notes = String::new();

    for line in lines {
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim();
        match key {
            "sdk_version" => sdk_version = unquote(value),
            "cli_version" => cli_version = unquote(value),
            "notes" => notes = unquote(value),
            "api_versions" => {
                api_versions = value
                    .trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .map(unquote)
                    .collect();
            }
            _ => {}
        }
    }

    CompatEntry {
        sdk_version,
        cli_version,
        api_versions,
        notes,
    }
}

fn unquote(s: &str) -> String {
    s.trim().trim_matches('"').to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_single_entry() {
        let toml = r#"
            # a comment
            [[entry]]
            sdk_version = "0.1.0"
            cli_version = "0.1.0"
            api_versions = ["v1", "v2"]
            notes = "Initial tracked compatibility entry."
        "#;
        let entries = parse_entries(toml);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].sdk_version, "0.1.0");
        assert_eq!(entries[0].cli_version, "0.1.0");
        assert_eq!(entries[0].api_versions, vec!["v1", "v2"]);
        assert_eq!(entries[0].notes, "Initial tracked compatibility entry.");
    }

    #[test]
    fn parses_multiple_entries() {
        let toml = r#"
            [[entry]]
            sdk_version = "0.1.0"
            cli_version = "0.1.0"
            api_versions = ["v1"]
            notes = "first"

            [[entry]]
            sdk_version = "0.2.0"
            cli_version = "0.2.0"
            api_versions = ["v1", "v2"]
            notes = "second"
        "#;
        let entries = parse_entries(toml);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[1].sdk_version, "0.2.0");
    }

    #[test]
    fn render_is_deterministic_and_consistent_with_source() {
        let entries = parse_entries(
            r#"
            [[entry]]
            sdk_version = "0.1.0"
            cli_version = "0.1.0"
            api_versions = ["v1", "v2"]
            notes = "n"
            "#,
        );
        let rendered_once = render(&entries);
        let rendered_twice = render(&entries);
        assert_eq!(rendered_once, rendered_twice);
        assert!(rendered_once.contains("| 0.1.0 | 0.1.0 | v1, v2 | n |"));
    }

    #[test]
    fn ensure_matrix_has_entry_for_matches_sdk_or_cli_version() {
        let entries = parse_entries(
            r#"
            [[entry]]
            sdk_version = "1.2.3"
            cli_version = "9.9.9"
            api_versions = ["v1"]
            notes = "n"
            "#,
        );
        assert!(entries
            .iter()
            .any(|e| e.sdk_version == "1.2.3" || e.cli_version == "1.2.3"));
        assert!(!entries
            .iter()
            .any(|e| e.sdk_version == "0.0.0" || e.cli_version == "0.0.0"));
    }
}
